.TH AUTOSCAN 1 "2026-06-20" "autoconf-rs 0.1" "User Commands"
.SH NAME
autoscan \- scan C sources for Autoconf hints
.SH SYNOPSIS
.B autoscan
[\fIOPTION\fR]... [\fISRCDIR\fR]
.SH DESCRIPTION
Scan C source files and generate configure.scan with
suggested Autoconf macros.
.SH "SEE ALSO"
\fBautoconf\fR(1)
