.TH AUTOUPDATE 1 "2026-06-20" "autoconf-rs 0.1" "User Commands"
.SH NAME
autoupdate \- update obsolete Autoconf macros
.SH SYNOPSIS
.B autoupdate
[\fIFILE\fR]...
.SH DESCRIPTION
Update obsolete Autoconf macros in configure.ac. Maps 60+
deprecated macro names to their modern replacements.
.SH "SEE ALSO"
\fBautoconf\fR(1)
