.TH IFNAMES 1 "2026-06-20" "autoconf-rs 0.1" "User Commands"
.SH NAME
ifnames \- extract preprocessor conditionals from C sources
.SH SYNOPSIS
.B ifnames
[\fIFILE\fR]...
.SH DESCRIPTION
Extract #if, #ifdef, #ifndef, #elif, and #else directive names
from C source files for use with autoheader.
.SH "SEE ALSO"
\fBautoheader\fR(1)
