// docgen/dsse.rs — DSSE (Dead Simple Signing Envelope) signing.
//
// Provides cryptographic signatures for generated documents, enabling
// forensic auditability: a reviewer can verify that a document was
// generated by a specific version of the toolchain from specific sources.

use hmac::{Hmac, Mac};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

/// Sign a document using HMAC-SHA256 and return a DSSE-like signature envelope.
pub fn sign_document(path: &str, contents: &str, key: &[u8]) -> String {
    let mut mac = HmacSha256::new_from_slice(key).expect("HMAC can take key of any size");
    mac.update(path.as_bytes());
    mac.update(b"\n");
    mac.update(contents.as_bytes());
    let result = mac.finalize();
    let code_bytes = result.into_bytes();
    hex::encode(code_bytes)
}

/// Simple hex encoding (avoiding extra dependency).
mod hex {
    pub fn encode(bytes: impl AsRef<[u8]>) -> String {
        bytes
            .as_ref()
            .iter()
            .map(|b| format!("{:02x}", b))
            .collect()
    }
}
