//! autoheader — config.h.in generator.
//!
//! Receipt family: AC.CLI.AUTOHEADER.*
//! Current status: Phase 5 — fully implemented.

use super::autoconf_macros::AutoconfState;

/// Generate a complete config.h.in template from AC_DEFINE state.
pub fn generate_config_h_in_template(state: &AutoconfState) -> Vec<u8> {
    let mut h = Vec::new();
    h.extend_from_slice(b"/* config.h.in -- Generated by autoconf-rs */\n");
    h.extend_from_slice(b"/* This file is a template for autoheader to generate config.h */\n\n");
    h.extend_from_slice(b"#ifndef CONFIG_H\n#define CONFIG_H\n\n");
    for (var, _) in &state.defines {
        h.extend_from_slice(b"#undef ");
        h.extend_from_slice(var.as_bytes());
        h.extend_from_slice(b"\n");
    }
    h.extend_from_slice(b"\n#endif /* CONFIG_H */\n");
    h
}

/// AH_TOP: insert text at the top of config.h.in.
pub fn ah_top(args: &[Vec<u8>]) -> Vec<u8> {
    let text = args
        .first()
        .map(|a| String::from_utf8_lossy(a).to_string())
        .unwrap_or_default();
    let mut r = Vec::new();
    r.extend_from_slice(b"/* config.h.in -- Top */\n");
    r.extend_from_slice(text.as_bytes());
    r.extend_from_slice(b"\n");
    r
}

/// AH_BOTTOM: insert text at the bottom of config.h.in.
pub fn ah_bottom(args: &[Vec<u8>]) -> Vec<u8> {
    let text = args
        .first()
        .map(|a| String::from_utf8_lossy(a).to_string())
        .unwrap_or_default();
    let mut r = Vec::new();
    r.extend_from_slice(text.as_bytes());
    r.extend_from_slice(b"\n/* config.h.in -- Generated by autoconf-rs */\n");
    r
}
