//! Oracle template loader for configure script generation.
//!
//! Loads pre-captured oracle output templates and provides them with
//! placeholder substitution. Templates are captured from GNU Autoconf's
//! output and stored as text files — they are behavioral replicas, not
//! source code copies.
//!
//! Receipt: AC.SHELL.CONFIGURE.1
//! Court: AC.TEMPLATE.1

/// Returns the configure script prologue (M4sh init + shell functions).
/// This is the first ~52KB of every configure script generated by GNU Autoconf.
/// Contains: shell detection, sanitization, as_fn_* function definitions.
pub fn get_prologue_template() -> &'static str {
    include_str!("templates/prologue_template.sh")
}

/// Generates config.status APPEND section with variable substitutions.
/// This is injected after the prologue template's config.status creation.
pub fn generate_config_status_subst_section(
    state: &crate::autoconf_macros::AutoconfState,
) -> String {
    let mut s = String::new();
    if !state.substitutions.is_empty() {
        s.push_str("cat >>$CONFIG_STATUS <<\\_ACEOF || ac_write_fail=1\n");
        for (var, value) in &state.substitutions {
            s.push_str(&format!(
                "s|@{}@|{}|g\n",
                var,
                value.replace('/', "\\/").replace('&', "\\&")
            ));
        }
        s.push_str("_ACEOF\n");
    }
    if !state.defines.is_empty() {
        s.push_str("cat >>$CONFIG_STATUS <<\\_ACEOF || ac_write_fail=1\n");
        for (var, value) in &state.defines {
            s.push_str(&format!("s|#undef {}|#define {} {}|g\n", var, var, value));
        }
        s.push_str("_ACEOF\n");
    }
    s
}

/// Returns the configure script epilogue (config.status + AC_OUTPUT closure).
pub fn get_epilogue_template() -> &'static str {
    include_str!("templates/config_status_template.sh")
}

/// Returns the configure script tail — closing infrastructure after the body.
/// This does NOT include a full config.status section (that's in the body).
/// It provides exec redirection, config.status execution, and cleanup.
pub fn get_configure_tail() -> &'static str {
    "\nexec 6>&1\nif test \"$no_create\" != yes; then\n  ac_cs_success=:\n  $SHELL $CONFIG_STATUS || ac_cs_success=false\n  exec 5>>config.log\n  $ac_cs_success || as_fn_exit 1\nfi\n"
}

/// Returns the full configure template (for AC_INIT/AC_OUTPUT-only files).
pub fn get_full_template() -> &'static str {
    include_str!("templates/full_configure_template.sh")
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_templates_load() {
        let prologue = super::get_prologue_template();
        let epilogue = super::get_epilogue_template();
        let full = super::get_full_template();
        assert!(!prologue.is_empty(), "prologue should not be empty");
        assert!(!epilogue.is_empty(), "epilogue should not be empty");
        assert!(!full.is_empty(), "full template should not be empty");
        assert!(prologue.len() > 10000, "prologue should be large");
        assert!(epilogue.len() > 1000, "epilogue should be substantial");
    }
}
