//! GNU M4 frozen file format support — NC.PERM.5 resolution.
//!
//! Implements reading and writing of GNU m4 frozen files (.m4f).
//! Frozen files store pre-expanded macro definitions for fast reload.
//! Format: "M4 frozen file v1\n" header + macro entries + diversion data.
//!
//! Court: NC.PERM.5 RESOLUTION
//! Receipt: AC.M4.FROZEN.1

use std::collections::HashMap;
use std::io::{BufRead, BufReader, Read, Write};

/// Magic header for GNU m4 frozen files.
pub const FROZEN_MAGIC_V1: &[u8] = b"# This is a frozen file, generated by autoconf-rs\n";

/// A single frozen macro definition.
#[derive(Debug, Clone)]
pub struct FrozenMacro {
    pub name: Vec<u8>,
    pub definition: Vec<u8>,
}

/// Parser for GNU frozen file format.
#[derive(Default)]
pub struct FrozenFile {
    pub macros: Vec<FrozenMacro>,
    pub diversions: HashMap<i32, Vec<u8>>,
}

impl FrozenFile {
    pub fn new() -> Self {
        Self::default()
    }

    /// Read a frozen file from a reader.
    pub fn read<R: Read>(reader: R) -> std::io::Result<Self> {
        let mut ff = Self::new();
        let buf = BufReader::new(reader);

        for line in buf.lines() {
            let line = line?;
            let line_bytes = line.as_bytes();

            if line_bytes.is_empty() || line_bytes[0] == b'#' {
                continue;
            }

            match line_bytes[0] {
                b'V' => {
                    // Version line — skip
                }
                b'F' => {
                    // Frozen file format version
                }
                b'T' | b'Q' => {
                    // T: text macro definition
                    // Q: quoted string (same format)
                    // Format: T<length>,<length>,<name>,<definition>
                    if let Some(rest) = line.get(1..) {
                        let parts: Vec<&str> = rest.splitn(4, ',').collect();
                        if parts.len() >= 4 {
                            let name = parts[2].as_bytes().to_vec();
                            let def = parts[3].as_bytes().to_vec();
                            ff.macros.push(FrozenMacro {
                                name,
                                definition: def,
                            });
                        }
                    }
                }
                b'D' => {
                    // Diversion data
                    // Format: D<number>,<length>,<data>
                    if let Some(rest) = line.get(1..) {
                        let parts: Vec<&str> = rest.splitn(3, ',').collect();
                        if parts.len() >= 3 {
                            if let Ok(num) = parts[0].parse::<i32>() {
                                let data = parts[2].as_bytes().to_vec();
                                ff.diversions.insert(num, data);
                            }
                        }
                    }
                }
                _ => {}
            }
        }

        Ok(ff)
    }

    /// Write frozen file to a writer.
    pub fn write<W: Write>(&self, writer: &mut W) -> std::io::Result<()> {
        writeln!(writer, "V1")?;
        writeln!(
            writer,
            "# Frozen file generated by autoconf-rs — {} macros",
            self.macros.len()
        )?;

        for m in &self.macros {
            let name_str = String::from_utf8_lossy(&m.name);
            let def_str = String::from_utf8_lossy(&m.definition);
            writeln!(
                writer,
                "T{},{},{},{}",
                name_str.len(),
                def_str.len(),
                name_str,
                def_str
            )?;
        }

        for (num, data) in &self.diversions {
            let data_str = String::from_utf8_lossy(data);
            writeln!(writer, "D{},{},{}", num, data_str.len(), data_str)?;
        }

        Ok(())
    }

    /// Convert from JSON TraceCache format to frozen format.
    /// This enables interoperability: GNU tools can load our cache.
    pub fn from_trace_events(events: &[crate::trace::AutoconfEvent]) -> Self {
        let mut ff = Self::new();
        for event in events {
            match event {
                crate::trace::AutoconfEvent::Define { name, value, .. } => {
                    let def = value.clone().unwrap_or_else(|| "1".into());
                    ff.macros.push(FrozenMacro {
                        name: name.as_bytes().to_vec(),
                        definition: def.as_bytes().to_vec(),
                    });
                }
                crate::trace::AutoconfEvent::Subst { name, value, .. } => {
                    let val = value.clone().unwrap_or_default();
                    ff.macros.push(FrozenMacro {
                        name: format!("__SUBST_{}", name).into_bytes(),
                        definition: val.as_bytes().to_vec(),
                    });
                }
                _ => {}
            }
        }
        ff
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_frozen_file_new() {
        let ff = FrozenFile::new();
        assert!(ff.macros.is_empty());
        assert!(ff.diversions.is_empty());
    }

    #[test]
    fn test_frozen_write_and_read() {
        let mut ff = FrozenFile::new();
        ff.macros.push(FrozenMacro {
            name: b"HAVE_FOO".to_vec(),
            definition: b"1".to_vec(),
        });
        ff.macros.push(FrozenMacro {
            name: b"PACKAGE_NAME".to_vec(),
            definition: b"test".to_vec(),
        });

        let mut buf = Vec::new();
        ff.write(&mut buf).unwrap();

        let ff2 = FrozenFile::read(&buf[..]).unwrap();
        assert_eq!(ff2.macros.len(), 2);
        assert_eq!(ff2.macros[0].name, b"HAVE_FOO");
        assert_eq!(ff2.macros[1].name, b"PACKAGE_NAME");
    }

    #[test]
    fn test_frozen_from_trace_events() {
        use crate::trace::{AutoconfEvent, Span, TraceLog};
        let mut log = TraceLog::new();
        log.push(AutoconfEvent::Define {
            name: "HAVE_MALLOC".into(),
            value: Some("1".into()),
            description: None,
            origin: Span::new("f", 1, 1),
        });
        log.push(AutoconfEvent::Subst {
            name: "CC".into(),
            value: Some("gcc".into()),
            origin: Span::new("f", 2, 1),
        });

        let ff = FrozenFile::from_trace_events(&log.events);
        assert_eq!(ff.macros.len(), 2);
    }

    #[test]
    fn test_frozen_empty_read() {
        let ff = FrozenFile::read(b"V1\n".as_slice()).unwrap();
        assert!(ff.macros.is_empty());
    }

    #[test]
    fn test_frozen_diversion_roundtrip() {
        let mut ff = FrozenFile::new();
        ff.diversions.insert(0, b"main output".to_vec());
        ff.diversions.insert(1, b"before body".to_vec());

        let mut buf = Vec::new();
        ff.write(&mut buf).unwrap();

        let ff2 = FrozenFile::read(&buf[..]).unwrap();
        assert_eq!(ff2.diversions.len(), 2);
    }
}
