//! Shell script generator for Autoconf.
//!
//! Assembles expanded M4 output into a complete POSIX-compliant configure
//! shell script. Handles quoting, escaping, here-documents, variable
//! substitution, and the configure/config.status two-phase output.
//!
//! Receipt family: AC.SHELL.*
//! Status: Phase 5 — full configure generation with shell sanitization (panel mandate).

/// Generates a configure shell script from parsed Autoconf input.
pub struct ShellGenerator;

impl ShellGenerator {
    pub fn new() -> Self {
        Self
    }

    /// Generate a configure script from a ConfigureAc and expanded M4 output.
    pub fn generate(&self, ac: &super::ConfigureAc, expanded_m4: &str) -> String {
        let mut script = String::new();

        // Shell shebang
        script.push_str("#! /bin/sh\n");

        // Header comment
        if let Some(ref name) = ac.package_name {
            if let Some(ref version) = ac.package_version {
                script.push_str(&format!(
                    "# Generated by autoconf-rs for {} {}\n",
                    name, version
                ));
            }
        }
        script.push_str("# Forensic-parity GNU Autoconf reimplementation\n\n");

        // Phase 1: copy expanded M4 output directly
        // Future phases will add proper shell quoting, diversion ordering,
        // config.status generation, and template substitution.
        script.push_str(expanded_m4);

        script
    }
}

impl Default for ShellGenerator {
    fn default() -> Self {
        Self::new()
    }
}

/// Generate a minimal but working configure script with dynamic substitutions.
/// Used when configure.ac has AC_SUBST/AC_CONFIG_FILES/AC_DEFINE/etc.
/// Court: AC.SHELL.DYNAMIC.1
pub fn generate_dynamic_configure(
    state: &super::autoconf_macros::AutoconfState,
    name: &str,
    version: &str,
) -> String {
    let mut s = String::new();

    // Start with full M4sh init prologue (oracle-captured, 52KB)
    // This provides shell portability, variable reset, locale setup,
    // CONFIG_SHELL re-exec, shell functions, and sanitization —
    // matching GNU Autoconf byte-for-byte on the prologue section.
    let prologue = include_str!("templates/prologue_template.sh")
        .replace("{NAME}", name)
        .replace("{VERSION}", version)
        .replace("{BUGREPORT}", state.bug_report.as_deref().unwrap_or(""))
        .replace("Generated by GNU Autoconf 2.73", "Generated by autoconf-rs");
    s.push_str(&prologue);

    // Inject bug report line and unique file after prologue header
    if let Some(ref bug) = state.bug_report {
        s.push_str(&format!("# Report bugs to <{}>.\n", bug));
    }
    if let Some(ref unique) = state.unique_file {
        s.push_str(&format!("ac_unique_file=\"{}\"\n", unique));
    }

    // CROSS.014: config.site — source system-wide site defaults
    s.push_str("# Site configuration\n");
    s.push_str("if test \"$CONFIG_SITE\" != \"/dev/null\"; then\n");
    s.push_str("  if test -r \"${CONFIG_SITE-/usr/local/share/config.site}\"; then\n");
    s.push_str("    . \"${CONFIG_SITE-/usr/local/share/config.site}\" 2>/dev/null || :\n");
    s.push_str("  fi\n");
    s.push_str("  if test -r \"${CONFIG_SITE-/usr/local/etc/config.site}\"; then\n");
    s.push_str("    . \"${CONFIG_SITE-/usr/local/etc/config.site}\" 2>/dev/null || :\n");
    s.push_str("  fi\n");
    s.push_str("fi\n\n");

    // Shell helper functions for compile/link/run tests
    // These are required by AC_CHECK_FUNCS, AC_CHECK_HEADERS, AC_COMPILE_IFELSE, etc.
    // Without them, generated configure scripts fail at runtime with
    // "ac_fn_c_try_link: command not found".
    s.push_str("\n# Autoconf shell helper functions\n");
    s.push_str("ac_fn_c_try_compile() {\n");
    s.push_str("  rm -f conftest.$ac_objext conftest$ac_exeext\n");
    s.push_str("  if { (eval \"$ac_compile\") >&5; } && test -s conftest.$ac_objext; then\n");
    s.push_str("    ac_retval=0\n");
    s.push_str("  else\n");
    s.push_str("    printf '%s\\n' \"configure: failed program was:\" >&5\n");
    s.push_str("    cat conftest.$ac_ext >&5\n");
    s.push_str("    ac_retval=1\n");
    s.push_str("  fi\n");
    s.push_str("  rm -f conftest.$ac_objext conftest.$ac_ext\n");
    s.push_str("  return $ac_retval\n");
    s.push_str("}\n\n");

    s.push_str("ac_fn_c_try_link() {\n");
    s.push_str("  rm -f conftest.$ac_objext conftest$ac_exeext\n");
    s.push_str("  if { (eval \"$ac_link\") >&5; } && test -s conftest$ac_exeext; then\n");
    s.push_str("    ac_retval=0\n");
    s.push_str("  else\n");
    s.push_str("    printf '%s\\n' \"configure: failed program was:\" >&5\n");
    s.push_str("    cat conftest.$ac_ext >&5\n");
    s.push_str("    ac_retval=1\n");
    s.push_str("  fi\n");
    s.push_str("  rm -f conftest.$ac_objext conftest.$ac_ext conftest$ac_exeext\n");
    s.push_str("  return $ac_retval\n");
    s.push_str("}\n\n");

    s.push_str("ac_fn_c_try_run() {\n");
    s.push_str(
        "  if { ac_try='$ac_link'; (eval \"$ac_try\") >&5; } && test -s conftest$ac_exeext &&\n",
    );
    s.push_str("     { ac_try='./conftest$ac_exeext'; { (eval \"$ac_try\") >&5; }; }; then\n");
    s.push_str("    ac_retval=0\n");
    s.push_str("  else\n");
    s.push_str("    printf '%s\\n' \"configure: failed program was:\" >&5\n");
    s.push_str("    cat conftest.$ac_ext >&5\n");
    s.push_str("    ac_retval=1\n");
    s.push_str("  fi\n");
    s.push_str("  rm -f conftest.$ac_ext conftest$ac_exeext\n");
    s.push_str("  return $ac_retval\n");
    s.push_str("}\n\n");

    s.push_str("ac_fn_c_try_cpp() {\n");
    s.push_str("  rm -f conftest.$ac_objext conftest$ac_exeext\n");
    s.push_str(
        "  if { (eval \"$ac_cpp conftest.$ac_ext\") >&5; } && test -s conftest.$ac_objext; then\n",
    );
    s.push_str("    ac_retval=0\n");
    s.push_str("  else\n");
    s.push_str("    printf '%s\\n' \"configure: failed program was:\" >&5\n");
    s.push_str("    cat conftest.$ac_ext >&5\n");
    s.push_str("    ac_retval=1\n");
    s.push_str("  fi\n");
    s.push_str("  rm -f conftest.$ac_objext conftest.$ac_ext\n");
    s.push_str("  return $ac_retval\n");
    s.push_str("}\n\n");

    // Dynamic feature test body (AC_CHECK_*, AC_C_*, etc.)
    // Generated from prescan state — inserted after M4sh init prologue
    let feature_body = crate::configure_body::generate_feature_test_body(state);
    let feature_str = String::from_utf8_lossy(&feature_body);
    let has_actual_tests = state.has_compiler_check
        || !state.checked_funcs.is_empty()
        || !state.checked_headers.is_empty()
        || !state.checked_libs.is_empty()
        || !state.checked_types.is_empty()
        || !state.checked_progs.is_empty()
        || !state.checked_sizeofs.is_empty()
        || !state.c_conformance_checks.is_empty();
    if has_actual_tests {
        s.push_str("# Feature tests\n");
        s.push_str(&feature_str);
        s.push('\n');
    }

    // Set PACKAGE_BUGREPORT from AC_INIT third arg
    s.push_str(&format!(
        "PACKAGE_BUGREPORT='{}'\n",
        state.bug_report.as_deref().unwrap_or("")
    ));

    // Note: The prologue template already includes ac_subst_vars, variable defaults,
    // host/build triple detection, and directory defaults. We only add what's specific
    // to this configure.ac: program detection variables and explicit substitutions.

    // Explicit substitution variables from AC_SUBST
    for (var, value) in &state.substitutions {
        if !value.is_empty() {
            s.push_str(&format!("{}='{}'\n", var, value));
        }
    }

    // Stamp file support — tracks when config.status was last run
    s.push_str("# Stamp file support for dependency tracking\n");
    s.push_str("ac_config_stamp=\"\"\n");
    s.push_str("# Compare new Makefile with existing to avoid unnecessary rebuilds\n");
    s.push_str("ac_config_update() {\n");
    s.push_str("  if test -f \"$1\" && cmp -s \"$2\" \"$1\"; then\n");
    s.push_str("    rm -f \"$2\"\n");
    s.push_str("  else\n");
    s.push_str("    mv -f \"$2\" \"$1\"\n");
    s.push_str("    printf '%s\\n' \"updated $1\"\n");
    s.push_str("  fi\n}\n\n");

    // Ensure substitution function uses final variable values
    s.push_str("\n# Variable substitution helper\n");
    s.push_str("substitute() {\n");
    s.push_str("  # Create output directory if needed\n");
    s.push_str("  mkdir -p \"$(dirname \"$2\")\" 2>/dev/null || :\n");
    s.push_str("  sed");
    // Always substitute standard Autoconf variables
    s.push_str(&format!(" -e 's|@PACKAGE_NAME@|{}|g'", name));
    s.push_str(&format!(" -e 's|@PACKAGE_VERSION@|{}|g'", version));
    s.push_str(&format!(" -e 's|@PACKAGE_STRING@|{} {}|g'", name, version));
    s.push_str(&format!(" -e 's|@PACKAGE_TARNAME@|{}|g'", name));
    s.push_str(" -e 's|@PACKAGE_BUGREPORT@||g'");
    s.push_str(" -e 's|@PACKAGE_URL@||g'");
    s.push_str(" -e 's|@srcdir@|$srcdir|g'");
    s.push_str(" -e 's|@prefix@|$prefix|g'");
    s.push_str(" -e 's|@exec_prefix@|$exec_prefix|g'");
    // Explicit substitutions (always include, even for empty values)
    for (var, value) in &state.substitutions {
        let escaped_val = if value.is_empty() {
            match var.as_str() {
                "PACKAGE_NAME" => name.replace('&', "\\&").replace('/', "\\/"),
                "PACKAGE_VERSION" => version.replace('&', "\\&").replace('/', "\\/"),
                _ => String::new(),
            }
        } else {
            value.replace('&', "\\&").replace('/', "\\/")
        };
        s.push_str(&format!(" -e 's|@{}@|{}|g'", var, escaped_val));
    }
    s.push_str(" \"$1\" > \"$2\"\n");
    s.push_str("}\n\n");

    // Process config files
    for file in &state.config_files {
        s.push_str(&format!("printf '%s\\n' 'creating {}'\n", file));
        s.push_str(&format!("substitute '{}.in' '{}'\n", file, file));
    }

    // Process config headers
    for hdr in &state.config_headers {
        s.push_str(&format!("printf '%s\\n' 'creating {}'\n", hdr));
        s.push_str("sed");
        for (var, value) in &state.defines {
            s.push_str(&format!(
                " -e 's|#undef {}|#define {} {}|g'",
                var, var, value
            ));
        }
        s.push_str(&format!(" '{}.in' > '{}'\n", hdr, hdr));
    }

    s.push_str("\necho 'configure: creating config.status'\n");

    // --- Feature test body (C conformance, function checks, etc.) ---
    // Inserted here: after variable setup, before config.status generation.
    // Only emit if there are actual feature tests from the prescan.
    let feature_body = crate::configure_body::generate_feature_test_body(state);
    let feature_str = String::from_utf8_lossy(&feature_body);
    // Only emit if there are actual feature tests beyond just confdefs.h
    let has_actual_tests = state.has_compiler_check
        || !state.checked_funcs.is_empty()
        || !state.checked_headers.is_empty()
        || !state.checked_libs.is_empty()
        || !state.checked_types.is_empty()
        || !state.checked_progs.is_empty()
        || !state.checked_sizeofs.is_empty()
        || !state.c_conformance_checks.is_empty();
    if has_actual_tests {
        s.push_str("# Feature tests\n");
        s.push_str(&feature_str);
        s.push('\n');
    }

    // Write config.status with --recheck support
    s.push_str("cat >config.status <<\\_ACEOF\n");
    s.push_str("#! /bin/sh\n");
    s.push_str(&format!(
        "# Generated by autoconf-rs for {} {}\n",
        name, version
    ));
    // --recheck: re-run configure from config.status
    s.push_str("if test \"$1\" = --recheck; then\n");
    s.push_str(
        "  echo running CONFIG_SHELL=/bin/sh /bin/sh ./configure --no-create --no-recursion\n",
    );
    s.push_str("  exec /bin/sh ./configure --no-create --no-recursion\n");
    s.push_str("fi\n");
    s.push_str("substitute() {\n");
    s.push_str("  mkdir -p \"$(dirname \"$2\")\" 2>/dev/null || :\n");
    s.push_str("  sed");
    // Always substitute standard Autoconf variables
    s.push_str(&format!(" -e 's|@PACKAGE_NAME@|{}|g'", name));
    s.push_str(&format!(" -e 's|@PACKAGE_VERSION@|{}|g'", version));
    s.push_str(&format!(" -e 's|@PACKAGE_STRING@|{} {}|g'", name, version));
    s.push_str(&format!(" -e 's|@PACKAGE_TARNAME@|{}|g'", name));
    s.push_str(" -e 's|@PACKAGE_BUGREPORT@||g'");
    s.push_str(" -e 's|@PACKAGE_URL@||g'");
    s.push_str(" -e 's|@srcdir@|$srcdir|g'");
    s.push_str(" -e 's|@prefix@|$prefix|g'");
    s.push_str(" -e 's|@exec_prefix@|$exec_prefix|g'");
    // Explicit substitutions (always include, even for empty values)
    for (var, value) in &state.substitutions {
        let escaped_val = if value.is_empty() {
            match var.as_str() {
                "PACKAGE_NAME" => name.replace('&', "\\&").replace('/', "\\/"),
                "PACKAGE_VERSION" => version.replace('&', "\\&").replace('/', "\\/"),
                _ => String::new(),
            }
        } else {
            value.replace('&', "\\&").replace('/', "\\/")
        };
        s.push_str(&format!(" -e 's|@{}@|{}|g'", var, escaped_val));
    }
    s.push_str(" \"$1\" > \"$2\"\n");
    s.push_str("}\n");
    for file in &state.config_files {
        s.push_str(&format!(
            "substitute \"${{srcdir}}/{}.in\" '{}'\n",
            file, file
        ));
    }
    s.push_str("_ACEOF\n");
    s.push_str("chmod +x config.status\n");

    s
}

/// Generate only the config.status section (substitutions + heredoc).
/// Used when the full oracle-captured template provides the prologue.
pub fn generate_config_status_section(
    state: &super::autoconf_macros::AutoconfState,
    name: &str,
    version: &str,
) -> String {
    let mut s = String::new();

    // Write config.status for re-run capability
    s.push_str("cat >config.status <<\\_ACEOF\n");
    s.push_str("#! /bin/sh\n");
    s.push_str(&format!(
        "# Generated by autoconf-rs for {} {}\n",
        name, version
    ));
    s.push_str("substitute() {\n");
    s.push_str("  mkdir -p \"$(dirname \"$2\")\" 2>/dev/null || :\n");
    s.push_str("  sed");
    s.push_str(&format!(" -e 's|@PACKAGE_NAME@|{}|g'", name));
    s.push_str(&format!(" -e 's|@PACKAGE_VERSION@|{}|g'", version));
    s.push_str(&format!(" -e 's|@PACKAGE_STRING@|{} {}|g'", name, version));
    s.push_str(&format!(" -e 's|@PACKAGE_TARNAME@|{}|g'", name));
    s.push_str(&format!(
        " -e 's|@PACKAGE_BUGREPORT@|{}|g'",
        state.bug_report.as_deref().unwrap_or("")
    ));
    s.push_str(" -e 's|@PACKAGE_URL@||g'");
    s.push_str(" -e 's|@srcdir@|$srcdir|g'");
    s.push_str(" -e 's|@prefix@|$prefix|g'");
    s.push_str(" -e 's|@exec_prefix@|$exec_prefix|g'");
    for (var, value) in &state.substitutions {
        let escaped_val = if value.is_empty() {
            match var.as_str() {
                "PACKAGE_NAME" => name.replace('&', "\\&").replace('/', "\\/"),
                "PACKAGE_VERSION" => version.replace('&', "\\&").replace('/', "\\/"),
                "PACKAGE_BUGREPORT" => state
                    .bug_report
                    .as_deref()
                    .unwrap_or("")
                    .replace('&', "\\&")
                    .replace('/', "\\/"),
                _ => String::new(),
            }
        } else {
            value.replace('&', "\\&").replace('/', "\\/")
        };
        s.push_str(&format!(" -e 's|@{}@|{}|g'", var, escaped_val));
    }
    s.push_str(" \"$1\" > \"$2\"\n");
    s.push_str("}\n");
    for file in &state.config_files {
        s.push_str(&format!("substitute '{}.in' '{}'\n", file, file));
    }
    s.push_str("_ACEOF\n");
    s.push_str("chmod +x config.status\n");

    s
}

#[cfg(test)]
mod tests {
    use super::super::ConfigureAc;
    use super::*;

    #[test]
    fn test_generate_minimal() {
        let ac = ConfigureAc::parse("AC_INIT([test], [1.0])\nAC_OUTPUT\n");
        let gen = ShellGenerator::new();
        let script = gen.generate(&ac, "# configure script content\n");
        assert!(script.contains("#! /bin/sh"));
        assert!(script.contains("test"));
    }
}
